---
#Title : Geography 13 Lab 3
#Fernando Meza
#Subtitle: Lab 3 : Distances and the Border Zone
output:
  html_document:
    theme: journal
---
library(tidyverse)
library(sf)
library(units)
library(USAboundaries)
library(rnaturalearth)
library(gghighlight)
library(ggrepel)
library(knitr)
--- 
#1.1, 1.2
eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'xx`
USAboundaries::us_states(resolution = "low")

states = USAboundaries::us_states() %>%
filter(!stusps %in% c("HI", "PR", "AK") %>%
st_transform(eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'xx`)

#1.3, 1.4
State_Boundaries = rnaturalearth::countries110
State_Boundaries %>%
st_af_sf() %>%
filter(admin %in% c("Canada", "Mexico", "United States of America") %>%
st_transform(eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'xx`)

uscities <- read.csv("uscities.csv", TRUE, ",")
st_as_af(df,
  coords = c("X", "Y"), 
  crs = 4269))
filter(100 miles)

#2.1, 2.2
state_boundaries %>%
st_transform(State_Boundaries = Multilinestring) %>%
select(city_name, state, distance) %>%
(big3 = cities %>% 
   select(city, population) %>% 
   slice_max(population, n = 3))
#2.3, 2.4
State_Boundaries %>%
names(State_Boundaries)
filter(admin == "Mexico") %>%
st_distance(cities = farthest) %>%
slice_min(distance, n = 5) %>%
st_crs(big3)$units = "m"

ggplot(data = state_boundaries) + 
  geom_col(aes(x = reorder(city, -dist_to_sb), y = dist_to_sb)) + 
    labs(title = "Distance to Santa Barbara (km)") + 
  ggthemes::theme_fivethirtyeight() + 
  theme( axis.text.x = element_text(face = "bold", size = 14))
  
#3.1, 3.2
geom_sf()
lty()
?ggrepel::geom_label_repel
